#ifndef TTKWIDGETTOOLS_H
#define TTKWIDGETTOOLS_H

#include "stackedAnimationWidget/ttkanimationstackedwindow.h"
#include "transitionAnimationLabel/ttktransitionanimationwindow.h"
#include "gifLabelWidget/ttkgiflabelwindow.h"
#include "codeAreaWidget/ttkcodeareawindow.h"
#include "toastLabel/ttktoastwindow.h"
#include "marqueeWidget/ttkmarqueewindow.h"
#include "roundAnimationLabel/ttkroundanimationwindow.h"
#include "movingLabelSlider/ttkmovinglabelwindow.h"
#include "smoothMovingTableWidget/ttksmoothmovingtablewindow.h"
#include "colorDialog/ttkcolorwindow.h"
#include "layoutAnimationWidget/ttklayoutanimationwindow.h"
#include "shiningSlider/ttkshiningsliderwindow.h"
#include "splitItemLabel/ttksplititemwindow.h"
#include "grabItemWidget/ttkgrabitemwindow.h"
#include "funtionAnimationWidget/ttkfuntionanimationwindow.h"
#include "toolMenuWidget/ttktoolmenuwindow.h"
#include "moveDialog/ttkmovedialogwindow.h"
#include "moveWidget/ttkmovewidgetwindow.h"
#include "moveResizeWidget/ttkmoveresizewidgetwindow.h"
#include "circleClickPlane/ttkcircleclickplanewindow.h"
#include "lineEditWidget/ttklineeditwindow.h"
#include "toggleWidget/ttktogglewindow.h"
#include "radioButtonWidget/ttkradiobuttonwindow.h"
#include "checkButtonWidget/ttkcheckbuttonwindow.h"
#include "progressWidget/ttkprogresswindow.h"
#include "flatButtonWidget/ttkflatbuttonwindow.h"
#include "circularProgressWidget/ttkcircularprogresswindow.h"
#include "sliderWidget/ttksliderwindow.h"
#include "colorTablePlane/ttkcolortableplanewindow.h"

#endif // TTKWIDGETTOOLS_H
