# Author: Greedysky <greedysky@163.com>

name: win10

on: workflow_call

env:
  TTK_MODULE: TTKWidgetTools
  TTK_VERSTION: 3.1.0.0

jobs:
  build:
    name: Build on Qt6
    strategy:
      matrix:
        os: [windows-2022]

    env:
      QT_VERSION: 6.5.3

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Qt
        uses: actions/cache@v4
        with:
          path: ${{runner.workspace}}/Qt
          key: ${{runner.os}}-QtCache-${{env.QT_VERSION}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}
          host: windows
          arch: win64_mingw
          target: desktop
          modules: qt5compat qtscxml
          cache: 'true'

      - name: Create build dir
        shell: bash
        run: mkdir build
        working-directory: ${{runner.workspace}}

      - name: Build project
        shell: cmd
        run: |
          qmake -v
          cmake --version
          cmake ${{github.workspace}} -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DCMAKE_PREFIX_PATH=${{env.QT_ROOT_DIR}} -DTTK_QT_VERSION=6
          make -j2 && make install
        working-directory: ${{runner.workspace}}/build

      - name: Build package
        run: |
          # add dependency for openssl
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/openssl.7z -o openssl.7z
          7z x openssl.7z
          cp win64/*.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}
          # add dependency libraries and so on
          windeployqt ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}/${{env.TTK_MODULE}}.exe
          cp ${{runner.workspace}}/Qt/${{env.QT_VERSION}}/mingw_64/bin/Qt6Xml.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}
          cp ${{runner.workspace}}/Qt/${{env.QT_VERSION}}/mingw_64/bin/Qt6StateMachine.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSTION}}
          # remove usless library dependency
          ls -Filter "*.a" -Recurse | Remove-Item -Force
          # add portable binary package
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSTION}}-win10-x64.7z ${{env.TTK_MODULE}}
        working-directory: ${{runner.workspace}}/install

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSTION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: ${{runner.workspace}}/install/${{env.TTK_MODULE}}-${{env.TTK_VERSTION}}-win10-x64.7z
